apiVersion: v1
kind: Service
metadata:
  name: slytrade-paper
  namespace: slytrade
  labels:
    app.kubernetes.io/name: slytrade
    app.kubernetes.io/component: paper-trader
spec:
  selector:
    app.kubernetes.io/name: slytrade
    app.kubernetes.io/component: paper-trader
  ports:
    - name: metrics
      port: 9108
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
